In [71]:
## DATA Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\pdhar\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [72]:
## load the dataset
data = gutenberg.raw('shakespeare-macbeth.txt')
## save to file
with open("save.txt", 'w') as file:
    file.write(data)

In [ ]:
## data preprocessing
import numpy as np
from sklearn.model_selection import train_test_split
#from tensorflow.keras.preprocessing.text import Tokenizer
#from tensorflow.keras.preprocessing.sequence import pad_sequences

## load the dataset from file
with open("save.txt", 'r') as file:
    text = file.read().lower()

## Tokinization the text-creating indexes for words
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index) + 1
total_words
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'a': 6,
 'that': 7,
 'my': 8,
 'you': 9,
 'in': 10,
 'is': 11,
 'not': 12,
 'it': 13,
 'with': 14,
 'his': 15,
 'be': 16,
 'macb': 17,
 'your': 18,
 'our': 19,
 'haue': 20,
 'but': 21,
 'me': 22,
 'he': 23,
 'for': 24,
 'what': 25,
 'this': 26,
 'all': 27,
 'so': 28,
 'him': 29,
 'as': 30,
 'thou': 31,
 'we': 32,
 'enter': 33,
 'which': 34,
 'are': 35,
 'will': 36,
 'they': 37,
 'shall': 38,
 'no': 39,
 'then': 40,
 'macbeth': 41,
 'their': 42,
 'thee': 43,
 'vpon': 44,
 'on': 45,
 'macd': 46,
 'from': 47,
 'yet': 48,
 'thy': 49,
 'vs': 50,
 'come': 51,
 'king': 52,
 'now': 53,
 'at': 54,
 'hath': 55,
 'more': 56,
 'by': 57,
 'good': 58,
 'rosse': 59,
 'them': 60,
 'lady': 61,
 'would': 62,
 'time': 63,
 'was': 64,
 'do': 65,
 'who': 66,
 'like': 67,
 'her': 68,
 'if': 69,
 'should': 70,
 'did': 71,
 'when': 72,
 'there': 73,
 'say': 74,
 'were': 75,
 'where': 76,
 'doe': 77,
 'lord': 78,
 'make': 79,
 'or': 80,
 '1': 81,
 'must': 82,

In [74]:
## create input sequences
input_sequences = []
for line in text.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence) 

input_sequences

[[1, 885],
 [1, 885, 4],
 [1, 885, 4, 41],
 [1, 885, 4, 41, 57],
 [1, 885, 4, 41, 57, 1388],
 [1, 885, 4, 41, 57, 1388, 1389],
 [1, 885, 4, 41, 57, 1388, 1389, 1390],
 [418, 1391],
 [418, 1391, 1392],
 [418, 1391, 1392, 419],
 [270, 2],
 [270, 2, 886],
 [270, 2, 886, 33],
 [270, 2, 886, 33, 196],
 [270, 2, 886, 33, 196, 298],
 [81, 72],
 [81, 72, 38],
 [81, 72, 38, 32],
 [81, 72, 38, 32, 196],
 [81, 72, 38, 32, 196, 336],
 [81, 72, 38, 32, 196, 336, 131],
 [10, 270],
 [10, 270, 886],
 [10, 270, 886, 80],
 [10, 270, 886, 80, 10],
 [10, 270, 886, 80, 10, 1393],
 [128, 72],
 [128, 72, 1],
 [128, 72, 1, 1394],
 [128, 72, 1, 1394, 1395],
 [128, 72, 1, 1394, 1395, 84],
 [72, 1],
 [72, 1, 1396],
 [72, 1, 1396, 365],
 [72, 1, 1396, 365, 2],
 [72, 1, 1396, 365, 2, 887],
 [135, 7],
 [135, 7, 36],
 [135, 7, 36, 16],
 [135, 7, 36, 16, 172],
 [135, 7, 36, 16, 172, 1],
 [135, 7, 36, 16, 172, 1, 299],
 [135, 7, 36, 16, 172, 1, 299, 4],
 [135, 7, 36, 16, 172, 1, 299, 4, 666],
 [81, 76],
 [81, 76, 1],


In [75]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_sequence_len = max(len(x) for x in input_sequences)

input_sequences = np.array(
    pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))

input_sequences


array([[   0,    0,    0, ...,    0,    1,  885],
       [   0,    0,    0, ...,    1,  885,    4],
       [   0,    0,    0, ...,  885,    4,   41],
       ...,
       [   0,    0,    0, ..., 3552,    1,  885],
       [   0,    0,    0, ...,    1,  885,    4],
       [   0,    0,    0, ...,  885,    4,   41]],
      shape=(15245, 14), dtype=int32)

In [76]:
## create predictors and label
import tensorflow as tf
x,y = input_sequences[:,:-1],input_sequences[:,-1]
x


array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  885],
       [   0,    0,    0, ...,    1,  885,    4],
       ...,
       [   0,    0,    0, ...,    0, 3552,    1],
       [   0,    0,    0, ..., 3552,    1,  885],
       [   0,    0,    0, ...,    1,  885,    4]],
      shape=(15245, 13), dtype=int32)

In [77]:
# Extract the last column from input_sequences as labels (before one-hot encoding)
y_labels = input_sequences[:, -1]
y = tf.keras.utils.to_categorical(y_labels, num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(15245, 3553))

In [78]:
## split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [81]:
## train our LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional, Dropout
## define the model
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dropout(0.2))
model.add(Dense(total_words, activation='softmax'))

## compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

## build the model with input data to show proper shapes and params
model.build(input_shape=(None, max_sequence_len-1))
model.summary()

print(f"\nInput shape: {X_train.shape}")
print(f"Output shape: {y_train.shape}")
print(f"\nModel expects input shape: (batch_size, {max_sequence_len-1})")
print(f"Model outputs shape: (batch_size, {total_words})")

c:\Users\pdhar\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 13, 100)        │       355,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_14 (LSTM)                  │ (None, 13, 150)        │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_14 (Dropout)            │ (None, 13, 150)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_15 (LSTM)                  │ (None, 100)            │       100,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_15 (Dropout)            │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 3553)           │       358,853 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 965,153 (3.68 MB)

 Trainable params: 965,153 (3.68 MB)

 Non-trainable params: 0 (0.00 B)


Input shape: (12196, 13)
Output shape: (12196, 3553)

Model expects input shape: (batch_size, 13)
Model outputs shape: (batch_size, 3553)


In [82]:
## train the model 
history = model.fit(X_train,y_train,epochs=50,validation_data=(X_test,y_test),verbose=1)

Epoch 1/50
382/382 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - accuracy: 0.0343 - loss: 7.0101 - val_accuracy: 0.0377 - val_loss: 6.7695
Epoch 2/50
382/382 ━━━━━━━━━━━━━━━━━━━━ 12s 32ms/step - accuracy: 0.0360 - loss: 6.5840 - val_accuracy: 0.0377 - val_loss: 6.8698
Epoch 3/50
382/382 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.0396 - loss: 6.4747 - val_accuracy: 0.0433 - val_loss: 6.9762
Epoch 4/50
382/382 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.0439 - loss: 6.3903 - val_accuracy: 0.0430 - val_loss: 7.0564
Epoch 5/50
382/382 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.0446 - loss: 6.3125 - val_accuracy: 0.0449 - val_loss: 7.1089
Epoch 6/50
382/382 ━━━━━━━━━━━━━━━━━━━━ 15s 39ms/step - accuracy: 0.0465 - loss: 6.2258 - val_accuracy: 0.0446 - val_loss: 7.1292
Epoch 7/50
382/382 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.0473 - loss: 6.1330 - val_accuracy: 0.0453 - val_loss: 7.2073
Epoch 8/50
382/382 ━━━━━━━━━━━━━━━━━━━━ 15s 39ms/step - accuracy: 0.0506 - loss: 6.0378 - 

In [90]:
## predict the next word

model.save("next_word_model.h5")

import pickle
with open("tokenizer.pickle", "wb") as f:
    pickle.dump(tokenizer, f)

def predict_next_word(model, tokenizer, text_sequence, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text_sequence])[0]
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=-1)[0]
    
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None

In [84]:
input_text = "to be or not to"
print(f"Input text: {input_text}")
max_sequence_len = model.input_shape[1] + 1
next_word = predict_next_word(model, tokenizer, input_text, max_sequence_len)
print(f"Predicted next word: {next_word}")

Input text: to be or not to
Predicted next word: a


In [85]:
## save the model 
model.save("lstm_text_generator_model.h5")

## save the tokenizer
import pickle
with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)